[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[unix_http_server]
file=/run/supervisor.sock

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:svc]
command=/bin/bash -c 'python3 -c "import app" && exec socat TCP-LISTEN:6969,reuseaddr,fork EXEC:"python3 -u /app/app.py",pty,stderr'
directory=/app
autostart=true
autorestart=true
startretries=1000000
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
